### PR TITLE
update buildSuffixMap to build also custom colors from theme.

### PR DESCRIPTION
**Pull request by OrbisK**
Not all colors were available. (nested colors)

### CODE REVIEW

**Review by adoxography — CHANGES_REQUESTED** [review]
Looks good! Unfortunately, I can't merge when the lockfile is included in the PR.

**Comment by OrbisK** [comment]
Okay. Ill check tomorrow!

**Comment by adoxography** [comment]
Thanks! For future reference, you can just push to the PR's branch to update the PR, instead of having to open a brand new one. :)

**Comment by OrbisK** [comment]
> Thanks! For future reference, you can just push to the PR's branch to update the PR, instead of having to open a brand new one. :)

I know, thank you. I had no PC around. I used web ide to adjust this 😬

**Pull request closed without merging**
